name: notify_aur_upgrade
on:
  push:

jobs:
  Notify:
    name: Notify
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/lisuke/PKGBUILD/actions/workflows/xx-net.yml/dispatches \
            -d '{"ref":"xx-net"}'
